name: poultry_app
description: "A new Flutter project for managing poultry operations."

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0' # Ensure compatibility with Flutter/Dart SDK

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  url_launcher: ^6.2.1
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  supabase_flutter: ^2.0.2
  google_sign_in: ^6.1.6
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Linter for enforcing Flutter best practices

flutter:
  uses-material-design: true

  # Assets section
  assets:
    - assets/chicken-farm-banner-with-white-chicken-cartoon-character_1308-90659.jpg
    - assets/hen_151155842_1000.jpg
    - assets/raw-eggs-arrangement_23-2151864112.jpg
    - assets/vertical-closeup-shot-brown-chicken-blurred-background_181624-35804.jpg
    - assets/_MG_6048.JPG
    - assets/20221011_015355.jpg
    - assets/logo 5.jpg
    - assets/logo.jpg
    - assets/shoes.jpg
    - assets/w4vzlj.jpg
    - assets/google_logo.png
    - .env
